name: Release Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            name: uptime-kuma-push-linux-amd64
            toolchain: stable
            force-cross: false
          - target: aarch64-unknown-linux-gnu
            name: uptime-kuma-push-linux-arm64
            toolchain: stable
            force-cross: false
          - target: mips-unknown-linux-musl
            name: uptime-kuma-push-openwrt-mips
            toolchain: nightly-2024-05-21
            force-cross: false
          - target: x86_64-pc-windows-gnu
            name: uptime-kuma-push-windows-amd64
            toolchain: stable
            force-cross: false
          - target: x86_64-apple-darwin
            name: uptime-kuma-push-macos-amd64
            toolchain: stable
            force-cross: true
          - target: aarch64-apple-darwin
            name: uptime-kuma-push-macos-arm64
            toolchain: stable
            force-cross: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set OpenSSL ENV for MIPS
      if: matrix.target == 'mips-unknown-linux-musl'
      run: |
        echo "OPENSSL_DIR=/usr/lib" >> $GITHUB_ENV
        echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
        echo "MIPS_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR=/usr/lib" >> $GITHUB_ENV
        echo "MIPS_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV

    - name: Build binary
      uses: houseabsolute/actions-rust-cross@v1
      with:
        target: ${{ matrix.target }}
        toolchain: ${{ matrix.toolchain }}
        args: "--release"
        force-use-cross: ${{ matrix.force-cross }}

    - name: Rename and prepare artifact
      shell: bash
      run: |
        if [[ "${{ matrix.target }}" == *"-windows-"* ]]; then
          mv target/${{ matrix.target }}/release/uptime-kuma-push.exe ${{ matrix.name }}
        else
          mv target/${{ matrix.target }}/release/uptime-kuma-push ${{ matrix.name }}
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.name }}
