name: OpenWrt Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install cross
      run: cargo install cross
    - name: Build for OpenWrt (mips-unknown-linux-musl)
      run: cross build --target mips-unknown-linux-musl --release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: uptime-kuma-push-mips
        path: target/mips-unknown-linux-musl/release/uptime-kuma-push
